version: "3"
services:
  taskApp:
    image: task-app
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/task-db?useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      spring.jpa.hibernate.ddl-auto: update
  
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: on-failure
    volumes:
      - C:/myProjects/tmp/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=task-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes