version: "3"
services:
  taskApp:
    image: task-app
    restart: on-failure
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mysqldb
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=3306
      - DATABASE_NAME=task-db
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - C:/myProjects/tmp/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=task-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes